name: Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-docs-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v7
      - run: just docs
      - uses: actions/upload-artifact@v7
        with:
          name: html-docs
          path: "./docs/_build/html/"
  build-docs-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v7
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y fonts-cmu imagemagick
          # Allow SVG to PDF conversion in ImageMagick
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
      - name: Build LaTeX documentation
        run: just docs-latex
      - name: Compile PDF
        uses: xu-cheng/latex-action@v4
        with:
          os: alpine
          texlive_version: latest
          root_file: sphinxcontrib-bibtex-urn.tex
          compiler: latexmk
          args: -pdfxe -xelatex -interaction=nonstopmode -f
          continue_on_error: true
          working_directory: docs/_build/latex
          extra_system_packages: ghostscript
          xindy_parameters: -L english -C utf8 -M sphinx.xdy
      - uses: actions/upload-artifact@v7
        with:
          name: pdf-docs
          path: docs/_build/latex/sphinxcontrib-bibtex-urn.pdf
  deploy-docs:
    needs: [build-docs-html, build-docs-pdf]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download HTML artifact
        uses: actions/download-artifact@v8
        with:
          name: html-docs
          path: _site
      - name: Download PDF artifact
        uses: actions/download-artifact@v8
        with:
          name: pdf-docs
          path: _site
      - name: Upload merged pages artifact
        uses: actions/upload-pages-artifact@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
