name: Test
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3
      - uses: j178/prek-action@53276d8b0d10f8b6672aa85b4588c6921d0370cc # v2
  get-python-versions:
    uses: ./.github/workflows/get-python-versions.yml
  test-code:
    needs: get-python-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-versions) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3
      - name: Test with pytest
        run: just test ${{ (github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest') && '--cov=sphinxcontrib_bibtex_urn --cov-report=html --cov-report=xml' || '' }}
      - name: Generate coverage badge
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        run: uv run --group dev --group github genbadge coverage -i coverage.xml -o htmlcov/coverage.svg
      - name: Upload coverage report
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: htmlcov
  test-code-result:
    runs-on: ubuntu-latest
    needs: test-code
    if: always()
    steps:
      - name: Check test matrix results
        run: |
          if [[ "${NEEDS_TEST_CODE_RESULT}" == "success" ]]; then
            echo "All test jobs succeeded"
            exit 0
          else
            echo "One or more test jobs failed"
            exit 1
          fi
        env:
          NEEDS_TEST_CODE_RESULT: ${{ needs.test-code.result }}
